jobs:
  build:
    docker:
      - image: circleci/node:16.13

    working_directory: ~/repo/client

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install dependencies
          command: |
            npm i

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test

      - run:
          name: Publish to s3
          command: aws s3 cp build s3://cdk-react-test/ --recursive

  deploy:
    docker:
      - image: circleci/node:16.13

    working_directory: ~/repo/infrastructure

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install dependencies
          command: |
            sudo npm i -g aws-cdk
            npm i

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test

      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
