version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:16.13

    working_directory: ~/repo/client

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install dependencies
          command: |
            npm i

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test

      - aws-s3/copy:
          arguments: "--recursive"
          from: build
          to: "s3://cdk-react-test/"

  deploy:
    docker:
      - image: circleci/node:16.13

    working_directory: ~/repo/infrastructure

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install dependencies
          command: |
            sudo npm i -g aws-cdk
            npm i

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test

      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
